# deployment:
#   replicas: 5
#   image: stable-bookworm-perl
# service:
#   type: LoadBalancer
#   servicePort: 80
deployment:
  replicas: 5
  image: trixie-perl
service:
  type: LoadBalancer
  servicePort: 80
