apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: dp-demo
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      purpose: helm-demo
  template:
    metadata:
      labels:
        project: roboshop
        purpose: helm-demo
    spec:
      containers:
        - name: nginx
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: 80
