{% comment %} apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  #these are replicaset labels
  labels:
  project: roboshop
  purpose: dp-demo
spec:
  replicas: {{ .Values.deploymnent.replicas}}
  selector:
  # these labels are used to register pod
  matachlabels:
   project: roboshop
   purpose: helm-demo
#pod definition
template:
  metadata:
  name: Pod #it's written for pod 
  labels: 
    project: roboshop
    purpose: helm-demo
  spec:
   containers:
   - name: nginx
     image: {{ .Values.deploymnent.imageversion}} {% endcomment %}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: dp-demo
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      purpose: helm-demo
  template:
    metadata:
      labels:
        project: roboshop
        purpose: helm-demo
    spec:
      containers:
        - name: nginx
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: 80
