apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    purpose: helm-demo
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: 80
      nodePort: 30007