apiVersion: v1
kind: service
metadata:
  name: nginx-lb
spec:
  type: {{ .Version.service.type }}
  selector:
    project: roboshop
    purpose: helm-demo
  ports:
  -  protocal: TCP
     port: {{ .Version.service.servicePort }}
     targetport: 80